version: '3'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    networks:
      - isha-bim-net
    depends_on:
      - mongo
    environment:
        MONGO_URL: 'mongodb://mongo:27017'
        HTTP_PORT: 8000
      
  mongo:
    image: mongo:latest
    ports:
        - "27017:27017"
    volumes:
        - ./data:/data
    networks:
        - isha-bim-net

networks:
    isha-bim-net:
        driver: bridge
